import { PageHeader, PrimaryAction } from "@/components/PageHeader";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { formatCurrency } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { CirclePlus, ClipboardList, Loader2 } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

export default function AccountsPayable() {
  const [open, setOpen] = useState(false);
  const [description, setDescription] = useState("");
  const [dueDate, setDueDate] = useState("");
  const [amount, setAmount] = useState("");
  const [supplierId, setSupplierId] = useState("");
  const utils = trpc.useUtils();
  const accounts = trpc.finance.accounts.useQuery();
  const { data: suppliers } = trpc.catalog.suppliers.list.useQuery();
  const reset = () => { setOpen(false); setDescription(""); setDueDate(""); setAmount(""); setSupplierId(""); };
  const create = trpc.finance.createAccount.useMutation({ onSuccess: async () => { await utils.finance.accounts.invalidate(); reset(); toast.success("Conta registrada."); }, onError: error => toast.error(error.message) });
  const pay = trpc.finance.payAccount.useMutation({ onSuccess: async () => { await utils.finance.accounts.invalidate(); toast.success("Conta baixada como paga."); }, onError: error => toast.error(error.message) });
  const submit = (event: FormEvent) => { event.preventDefault(); create.mutate({ description, dueDate, amount: Number(amount), supplierId: supplierId ? Number(supplierId) : null }); };
  return <div className="mx-auto max-w-[1480px]"><PageHeader eyebrow="Financeiro" title="Contas a pagar" description="Acompanhe compromissos, vencimentos e pagamentos de fornecedores." action={<PrimaryAction onClick={() => setOpen(true)}><CirclePlus className="mr-2 h-4 w-4" />Nova conta</PrimaryAction>} />
    {accounts.error ? <div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800">Não foi possível carregar as contas. <button onClick={() => accounts.refetch()} className="font-bold underline">Tentar novamente</button></div> : <section className="overflow-hidden rounded-2xl border border-white/80 bg-white shadow-[0_10px_28px_rgba(16,24,32,0.06)]"><div className="grid grid-cols-[1fr_auto_auto] gap-3 border-b border-[#e5e8ec] bg-[#f7f8fa] px-5 py-3 text-[10px] font-bold uppercase tracking-[0.12em] text-slate-500"><span>Compromisso</span><span>Vencimento</span><span>Valor</span></div>{accounts.isLoading ? <div className="flex min-h-48 items-center justify-center"><Loader2 className="h-5 w-5 animate-spin text-[#a36c00]" /></div> : accounts.data?.length ? accounts.data.map(account => <div key={account.id} className="grid grid-cols-[minmax(0,1fr)_auto_auto] items-center gap-3 border-b border-[#edf0f2] px-5 py-4 last:border-0"><div className="min-w-0"><p className="truncate text-sm font-semibold text-[#101820]">{account.description}</p><p className="mt-1 truncate text-xs text-slate-500">{account.supplierName || "Sem fornecedor vinculado"}</p></div><div className="text-right"><p className="text-sm text-slate-700">{account.dueDate.split("-").reverse().join("/")}</p><span className={`text-xs font-semibold ${account.status === "paid" ? "text-emerald-700" : account.status === "overdue" ? "text-rose-700" : "text-amber-700"}`}>{account.status === "paid" ? "Pago" : account.status === "overdue" ? "Vencido" : "Em aberto"}</span></div><div className="text-right"><strong className="block text-sm text-[#101820]">{formatCurrency(account.amount)}</strong>{account.status !== "paid" ? <Button disabled={pay.isPending} onClick={() => pay.mutate({ id: account.id })} className="mt-1 h-7 rounded-md bg-[#173f32] px-2 text-xs text-white hover:bg-[#101820]">Baixar</Button> : null}</div></div>) : <div className="flex min-h-72 flex-col items-center justify-center px-5 text-center"><span className="flex h-14 w-14 items-center justify-center rounded-2xl bg-[#fff0c5] text-[#a36c00]"><ClipboardList className="h-6 w-6" /></span><h2 className="mt-5 font-serif text-xl font-semibold text-[#101820]">Nenhuma conta a pagar agora.</h2><p className="mt-2 max-w-md text-sm leading-6 text-slate-500">Cadastre os compromissos com fornecedores para acompanhar vencimentos e realizar as baixas no momento do pagamento.</p><Button onClick={() => setOpen(true)} className="mt-6 h-11 rounded-xl bg-[#e3aa14] text-[#101820] hover:bg-[#f5c243]"><CirclePlus className="mr-2 h-4 w-4" />Cadastrar primeira conta</Button></div>}</section>}
    <Dialog open={open} onOpenChange={isOpen => !isOpen && reset()}><DialogContent className="rounded-2xl sm:max-w-md"><DialogHeader><DialogTitle className="font-serif text-2xl text-[#101820]">Nova conta a pagar</DialogTitle></DialogHeader><form onSubmit={submit} className="space-y-4 pt-2"><label><span className="mb-1.5 block text-sm font-semibold text-[#101820]">Descrição</span><Input required value={description} onChange={event => setDescription(event.target.value)} placeholder="Ex.: Compra de bebidas" className="h-11 rounded-xl" /></label><label><span className="mb-1.5 block text-sm font-semibold text-[#101820]">Fornecedor</span><select value={supplierId} onChange={event => setSupplierId(event.target.value)} className="h-11 w-full rounded-xl border border-input bg-background px-3 text-sm"><option value="">Fornecedor opcional</option>{suppliers?.map(supplier => <option value={supplier.id} key={supplier.id}>{supplier.tradeName || supplier.legalName}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><label><span className="mb-1.5 block text-sm font-semibold text-[#101820]">Vencimento</span><Input required type="date" value={dueDate} onChange={event => setDueDate(event.target.value)} className="h-11 rounded-xl" /></label><label><span className="mb-1.5 block text-sm font-semibold text-[#101820]">Valor (R$)</span><Input required type="number" min="0.01" step="0.01" value={amount} onChange={event => setAmount(event.target.value)} placeholder="0,00" className="h-11 rounded-xl" /></label></div><div className="flex justify-end gap-2 pt-2"><Button type="button" variant="outline" onClick={reset} className="h-11 rounded-xl">Cancelar</Button><Button disabled={create.isPending} className="h-11 rounded-xl bg-[#e3aa14] text-[#101820] hover:bg-[#f5c243]">{create.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Salvar conta</Button></div></form></DialogContent></Dialog>
  </div>;
}
