import { PageHeader, PrimaryAction } from "@/components/PageHeader";
import { QueryAlert } from "@/components/QueryAlert";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { formatCurrency, formatDate, toNumber } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { ArrowDownFromLine, ArrowUpFromLine, CircleDollarSign, Landmark, Loader2, WalletCards } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

type DialogMode = "open" | "supply" | "withdrawal" | "close" | null;

export default function Cash() {
  const [mode, setMode] = useState<DialogMode>(null);
  const [amount, setAmount] = useState("");
  const [description, setDescription] = useState("");
  const utils = trpc.useUtils();
  const { user } = useAuth();
  const canManageSensitiveOperations = user?.role === "admin" || user?.role === "manager";
  const { data: session, isLoading, error: sessionError, refetch: refetchSession } = trpc.cash.status.useQuery(undefined, { refetchInterval: 15000 });
  const { data: cashData, error: movementsError, refetch: refetchMovements } = trpc.cash.movements.useQuery(undefined, { refetchInterval: 15000 });
  const refresh = async () => { await Promise.all([utils.cash.status.invalidate(), utils.cash.movements.invalidate(), utils.dashboard.summary.invalidate()]); };
  const openCash = trpc.cash.open.useMutation({ onSuccess: async () => { await refresh(); closeDialog(); toast.success("Caixa aberto com sucesso."); }, onError: error => toast.error(error.message) });
  const recordSupply = trpc.cash.recordSupply.useMutation({ onSuccess: async () => { await refresh(); closeDialog(); toast.success("Suprimento registrado."); }, onError: error => toast.error(error.message) });
  const recordMovement = trpc.cash.record.useMutation({ onSuccess: async () => { await refresh(); closeDialog(); toast.success("Movimentação registrada."); }, onError: error => toast.error(error.message) });
  const closeCash = trpc.cash.close.useMutation({ onSuccess: async result => { await refresh(); closeDialog(); toast.success(`Caixa fechado. Diferença: ${formatCurrency(result.difference)}.`); }, onError: error => toast.error(error.message) });
  const busy = openCash.isPending || recordSupply.isPending || recordMovement.isPending || closeCash.isPending;
  const closeDialog = () => { setMode(null); setAmount(""); setDescription(""); };
  const submit = (event: FormEvent) => { event.preventDefault(); const numericAmount = Number(amount); if (!Number.isFinite(numericAmount) || numericAmount < 0) { toast.error("Informe um valor válido."); return; } if (mode === "open") openCash.mutate({ openingAmount: numericAmount, notes: description || undefined }); if (mode === "supply") recordSupply.mutate({ amount: numericAmount, description: description || undefined }); if (mode === "withdrawal") recordMovement.mutate({ type: "withdrawal", amount: numericAmount, description: description || undefined }); if (mode === "close") closeCash.mutate({ actualClosingAmount: numericAmount, notes: description || undefined }); };
  const title = mode === "open" ? "Abrir caixa" : mode === "supply" ? "Registrar suprimento" : mode === "withdrawal" ? "Registrar sangria" : "Fechar caixa";
  const valueLabel = mode === "open" ? "Valor inicial (R$)" : mode === "close" ? "Valor contado (R$)" : "Valor (R$)";
  const movementLabel: Record<string, string> = { sale: "Venda", supply: "Suprimento", withdrawal: "Sangria", adjustment: "Ajuste", cancellation: "Cancelamento", return: "Devolução" };

  return <div className="mx-auto max-w-[1480px]"><PageHeader eyebrow="Operação" title="Caixa" description="Faça a abertura, acompanhe as vendas, registre sangrias e suprimentos, e realize o fechamento do turno." action={session ? canManageSensitiveOperations ? <PrimaryAction onClick={() => setMode("close")}><Landmark className="mr-2 h-4 w-4" />Fechar caixa</PrimaryAction> : <Button disabled className="h-11 rounded-xl">Fechamento restrito</Button> : <PrimaryAction onClick={() => setMode("open")}><WalletCards className="mr-2 h-4 w-4" />Abrir caixa</PrimaryAction>} />
    {sessionError ? <QueryAlert message="Não foi possível consultar o status do caixa." onRetry={() => refetchSession()} /> : null}
    {movementsError ? <QueryAlert message="Não foi possível carregar as movimentações do caixa." onRetry={() => refetchMovements()} /> : null}
    <section className="overflow-hidden rounded-2xl bg-[#173f32] shadow-[0_16px_36px_rgba(23,63,50,0.18)]"><div className="grid gap-6 p-6 text-white lg:grid-cols-[1fr_auto] lg:items-center lg:p-8"><div><p className="text-[10px] font-bold uppercase tracking-[0.17em] text-emerald-100/60">Status do turno</p><div className="mt-3 flex flex-wrap items-center gap-3"><h2 className="font-serif text-3xl font-semibold tracking-tight">{isLoading ? "Verificando caixa..." : session ? "Caixa aberto" : "Caixa fechado"}</h2><span className={`rounded-lg px-2.5 py-1 text-xs font-bold ${session ? "bg-emerald-100 text-emerald-900" : "bg-amber-100 text-amber-900"}`}>{session ? "Em operação" : "Aguardando abertura"}</span></div><p className="mt-3 max-w-lg text-sm leading-6 text-emerald-50/65">{session ? `Aberto em ${formatDate(session.openedAt)}. Todas as movimentações ficam registradas no histórico.` : "Informe o valor inicial para registrar as movimentações do dia e manter sua conciliação organizada."}</p></div><div className="rounded-2xl border border-white/10 bg-black/10 p-5 text-left lg:min-w-72"><p className="text-xs font-semibold uppercase tracking-[0.13em] text-emerald-100/55">Saldo esperado</p><p className="mt-2 font-serif text-3xl font-semibold">{formatCurrency(session?.expectedBalance)}</p><p className="mt-2 text-xs text-emerald-50/55">{session ? `Abertura: ${formatCurrency(session.openingAmount)}` : "Abra o caixa para iniciar a contagem."}</p></div></div></section>
    <section className="mt-6 grid gap-4 md:grid-cols-3"><button disabled={!session} onClick={() => setMode("supply")} className="rounded-2xl border border-white/80 bg-white p-5 text-left shadow-[0_10px_28px_rgba(37,59,48,0.06)] transition-transform enabled:hover:-translate-y-0.5 disabled:cursor-not-allowed disabled:opacity-50"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-100 text-emerald-800"><ArrowUpFromLine className="h-5 w-5" /></span><p className="mt-4 text-sm font-semibold text-[#294239]">Suprimento</p><p className="mt-1 text-sm leading-5 text-slate-500">Adicionar dinheiro ao caixa.</p></button><button disabled={!session || !canManageSensitiveOperations} onClick={() => setMode("withdrawal")} className="rounded-2xl border border-white/80 bg-white p-5 text-left shadow-[0_10px_28px_rgba(37,59,48,0.06)] transition-transform enabled:hover:-translate-y-0.5 disabled:cursor-not-allowed disabled:opacity-50"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-amber-100 text-amber-800"><ArrowDownFromLine className="h-5 w-5" /></span><p className="mt-4 text-sm font-semibold text-[#294239]">Sangria</p><p className="mt-1 text-sm leading-5 text-slate-500">{canManageSensitiveOperations ? "Retirar valores do caixa." : "Exige gerente ou administrador."}</p></button><button disabled={!session || !canManageSensitiveOperations} onClick={() => setMode("close")} className="rounded-2xl border border-white/80 bg-white p-5 text-left shadow-[0_10px_28px_rgba(37,59,48,0.06)] transition-transform enabled:hover:-translate-y-0.5 disabled:cursor-not-allowed disabled:opacity-50"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-200 text-slate-700"><Landmark className="h-5 w-5" /></span><p className="mt-4 text-sm font-semibold text-[#294239]">Fechamento</p><p className="mt-1 text-sm leading-5 text-slate-500">{canManageSensitiveOperations ? "Conferir e encerrar turno." : "Exige gerente ou administrador."}</p></button></section>
    <section className="mt-6 rounded-2xl border border-white/80 bg-white shadow-[0_10px_28px_rgba(37,59,48,0.06)]"><div className="flex items-center justify-between border-b border-[#e5ebe5] p-5 sm:p-6"><div><p className="text-xs font-bold uppercase tracking-[0.13em] text-slate-500">Movimentações</p><h2 className="mt-1 font-serif text-xl font-semibold text-[#17332c]">Histórico do caixa</h2></div><span className="rounded-lg bg-[#eef5ee] px-3 py-1.5 text-xs font-semibold text-emerald-800">{cashData?.movements.length ?? 0} registro(s)</span></div>{cashData?.movements.length ? <div>{cashData.movements.map(movement => { const isOutflow = movement.type === "withdrawal" || movement.type === "cancellation" || movement.type === "return"; return <div key={movement.id} className="grid grid-cols-[1fr_auto] gap-3 border-b border-[#edf0ed] px-5 py-4 last:border-0 sm:grid-cols-[1.5fr_1fr_1fr_auto]"><div><p className="text-sm font-semibold text-[#294239]">{movementLabel[movement.type]}</p><p className="mt-1 text-xs text-slate-500">{movement.description || "Sem observação"}</p></div><span className="hidden text-sm text-slate-500 sm:block">{formatDate(movement.createdAt)}</span><span className="hidden text-sm text-slate-500 sm:block">{movement.paymentMethod || "—"}</span><strong className={isOutflow ? "text-right text-amber-700" : "text-right text-emerald-800"}>{isOutflow ? "− " : "+ "}{formatCurrency(movement.amount)}</strong></div>; })}</div> : <div className="flex min-h-[220px] flex-col items-center justify-center px-5 text-center"><CircleDollarSign className="h-7 w-7 text-emerald-700/45" /><p className="mt-3 text-sm font-semibold text-[#294239]">Ainda não há movimentações.</p><p className="mt-1 text-sm text-slate-500">Vendas, suprimentos e sangrias aparecerão aqui.</p></div>}</section>
    <Dialog open={mode !== null} onOpenChange={isOpen => !isOpen && closeDialog()}><DialogContent className="rounded-2xl sm:max-w-md"><DialogHeader><DialogTitle className="font-serif text-2xl text-[#17332c]">{title}</DialogTitle><DialogDescription>{mode === "close" ? `Saldo esperado para este turno: ${formatCurrency(session?.expectedBalance)}.` : "Registre a operação para manter sua conciliação de caixa atualizada."}</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-4 pt-2"><label><span className="mb-1.5 block text-sm font-semibold text-[#294239]">{valueLabel}</span><Input required autoFocus type="number" min="0" step="0.01" value={amount} onChange={event => setAmount(event.target.value)} placeholder="0,00" className="h-11 rounded-xl" /></label><label><span className="mb-1.5 block text-sm font-semibold text-[#294239]">Observação</span><Input value={description} onChange={event => setDescription(event.target.value)} placeholder={mode === "withdrawal" ? "Ex.: retirada para cofre" : "Opcional"} className="h-11 rounded-xl" /></label><div className="flex justify-end gap-2 pt-2"><Button type="button" variant="outline" onClick={closeDialog} className="h-11 rounded-xl">Cancelar</Button><Button disabled={busy} className="h-11 rounded-xl bg-[#164e3d] text-white hover:bg-[#0f4032]">{busy && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Confirmar</Button></div></form></DialogContent></Dialog>
  </div>;
}
