import { PageHeader } from "@/components/PageHeader";
import { Button } from "@/components/ui/button";
import { QueryAlert } from "@/components/QueryAlert";
import { useAuth } from "@/_core/hooks/useAuth";
import { formatQuantity, toNumber } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, ArrowUpRight, BadgeAlert, CalendarClock, CircleCheck, ClipboardEdit, PackageSearch, RotateCcw, ShieldAlert } from "lucide-react";
import { useLocation } from "wouter";

function RiskCard({ label, value, detail, icon: Icon, tone }: { label: string; value: string; detail: string; icon: typeof ShieldAlert; tone: "amber" | "rose" | "slate" | "emerald" }) {
  const tones = {
    amber: "bg-amber-100 text-amber-800",
    rose: "bg-rose-100 text-rose-800",
    slate: "bg-slate-200 text-slate-700",
    emerald: "bg-emerald-100 text-emerald-800",
  };
  return <article className="rounded-2xl border border-white/80 bg-white p-5 shadow-[0_10px_28px_rgba(16,24,32,0.06)]"><div className="flex items-start justify-between gap-3"><p className="text-xs font-bold uppercase tracking-[0.13em] text-slate-500">{label}</p><span className={`flex h-9 w-9 items-center justify-center rounded-xl ${tones[tone]}`}><Icon className="h-[18px] w-[18px]" /></span></div><p className="mt-5 font-serif text-3xl font-semibold text-[#101820]">{value}</p><p className="mt-1.5 text-xs leading-5 text-slate-500">{detail}</p></article>;
}

export default function LossPrevention() {
  const [, setLocation] = useLocation();
  const { user } = useAuth();
  const canAccessLossPrevention = user?.role === "admin" || user?.role === "manager";
  const { data: report, isLoading, error, refetch } = trpc.reports.overview.useQuery(undefined, { enabled: canAccessLossPrevention });
  const lowStock = report?.lowStockItems ?? [];
  const expiring = report?.expiringBatches ?? [];
  const sensitiveCashEvents = (report?.latestCashMovements ?? []).filter(item => item.type === "cancellation" || item.type === "return");
  const riskCount = lowStock.length + expiring.length + (report?.lossCount ?? 0) + (report?.inventoryDivergence ? 1 : 0);

  if (!canAccessLossPrevention) return <div className="mx-auto grid min-h-[55vh] max-w-xl place-items-center px-4 text-center"><div><span className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-[#fff0c5] text-[#a36c00]"><ShieldAlert className="h-6 w-6" /></span><h1 className="mt-5 font-serif text-2xl font-semibold text-[#101820]">Acesso de gestão necessário</h1><p className="mt-3 text-sm leading-6 text-slate-500">O painel de prevenção de perdas reúne indicadores gerenciais e está disponível somente para gerente ou administrador.</p><Button onClick={() => setLocation("/")} className="mt-6 rounded-xl bg-[#e3aa14] text-[#101820] hover:bg-[#f5c243]">Voltar ao painel</Button></div></div>;

  return <div className="mx-auto max-w-[1480px]">
    <PageHeader eyebrow="Acompanhamento" title="Prevenção de perdas" description="Acompanhe os riscos que podem causar falta, vencimento, divergência ou perda financeira antes que afetem a operação." />
    {error ? <QueryAlert message="Não foi possível carregar os indicadores de prevenção de perdas." onRetry={() => refetch()} /> : null}
    {isLoading ? <div className="grid min-h-[320px] place-items-center text-sm text-slate-500">Carregando indicadores de risco...</div> : <>
      <section className="rounded-2xl bg-[#101820] p-5 text-white shadow-[0_16px_36px_rgba(16,24,32,0.18)] sm:p-6"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-4"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-[#f5c243]/20 text-[#f7d474]"><ShieldAlert className="h-5 w-5" /></span><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#f7d474]">Radar operacional</p><h2 className="mt-1 font-serif text-2xl font-semibold">{riskCount ? `${riskCount} ponto${riskCount === 1 ? "" : "s"} de atenção` : "Operação sob controle"}</h2><p className="mt-1.5 max-w-2xl text-sm leading-6 text-slate-300">O painel reúne estoque crítico, validade, perdas já registradas, divergências de inventário e reembolsos recentes.</p></div></div><Button onClick={() => setLocation("/relatorios")} variant="outline" className="h-10 shrink-0 rounded-xl border-white/20 bg-white/5 text-white hover:bg-white/10 hover:text-white">Ver relatórios <ArrowUpRight className="ml-1.5 h-4 w-4" /></Button></div></section>
      <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><RiskCard label="Estoque crítico" value={`${lowStock.length} item${lowStock.length === 1 ? "" : "s"}`} detail="No mínimo configurado ou abaixo dele" icon={PackageSearch} tone={lowStock.length ? "amber" : "emerald"} /><RiskCard label="Validade próxima" value={`${expiring.length} lote${expiring.length === 1 ? "" : "s"}`} detail="Com vencimento dentro de 7 dias" icon={CalendarClock} tone={expiring.length ? "rose" : "emerald"} /><RiskCard label="Perdas registradas" value={`${report?.lossCount ?? 0}`} detail={`${formatQuantity(report?.lossQuantity ?? 0)} unidade(s) baixadas`} icon={BadgeAlert} tone={(report?.lossCount ?? 0) ? "rose" : "emerald"} /><RiskCard label="Divergência inventário" value={formatQuantity(report?.inventoryDivergence ?? 0)} detail={`${report?.inventoryCount ?? 0} contagem(ns) registradas`} icon={ClipboardEdit} tone={(report?.inventoryDivergence ?? 0) ? "amber" : "slate"} /></section>
      <section className="mt-6 grid gap-6 xl:grid-cols-2"><article className="overflow-hidden rounded-2xl border border-white/80 bg-white shadow-[0_10px_28px_rgba(16,24,32,0.06)]"><div className="flex items-center justify-between border-b border-[#e5e8ec] p-5 sm:p-6"><div><p className="text-xs font-bold uppercase tracking-[0.13em] text-slate-500">Reposição</p><h2 className="mt-1 font-serif text-xl font-semibold text-[#101820]">Produtos com estoque crítico</h2></div><Button variant="ghost" onClick={() => setLocation("/estoque")} className="h-9 rounded-lg px-2 text-[#8a6207] hover:bg-[#fff6da] hover:text-[#6f4b00]">Estoque <ArrowUpRight className="ml-1 h-4 w-4" /></Button></div>{lowStock.length ? <div>{lowStock.map(item => <div key={item.id} className="flex items-center justify-between gap-4 border-b border-[#edf0f2] px-5 py-4 last:border-0 sm:px-6"><div className="min-w-0"><p className="truncate text-sm font-semibold text-[#203a31]">{item.name}</p><p className="mt-1 text-xs text-slate-500">Mínimo: {formatQuantity(item.minimumStock)} {item.unit} · Repor ao menos {formatQuantity(Math.max(toNumber(item.minimumStock) * 2 - toNumber(item.stockQuantity), 1))} {item.unit}</p></div><strong className={toNumber(item.stockQuantity) <= 0 ? "text-rose-700" : "text-amber-700"}>{formatQuantity(item.stockQuantity)} {item.unit}</strong></div>)}</div> : <div className="flex min-h-48 flex-col items-center justify-center px-5 text-center"><CircleCheck className="h-7 w-7 text-emerald-700/60" /><p className="mt-3 text-sm font-semibold text-[#294239]">Nenhum produto no estoque mínimo.</p><p className="mt-1 text-sm text-slate-500">Os produtos que precisarem de reposição aparecerão aqui.</p></div>}</article>
        <article className="overflow-hidden rounded-2xl border border-white/80 bg-white shadow-[0_10px_28px_rgba(16,24,32,0.06)]"><div className="flex items-center justify-between border-b border-[#e5e8ec] p-5 sm:p-6"><div><p className="text-xs font-bold uppercase tracking-[0.13em] text-slate-500">Vencimento</p><h2 className="mt-1 font-serif text-xl font-semibold text-[#101820]">Lotes próximos da validade</h2></div><Button variant="ghost" onClick={() => setLocation("/validade")} className="h-9 rounded-lg px-2 text-[#8a6207] hover:bg-[#fff6da] hover:text-[#6f4b00]">Validade <ArrowUpRight className="ml-1 h-4 w-4" /></Button></div>{expiring.length ? <div>{expiring.map(item => <div key={item.id} className="flex items-center justify-between gap-4 border-b border-[#edf0f2] px-5 py-4 last:border-0 sm:px-6"><div className="min-w-0"><p className="truncate text-sm font-semibold text-[#203a31]">{item.productName}</p><p className="mt-1 text-xs text-slate-500">Lote {item.code || "sem identificação"} · {formatQuantity(item.availableQuantity)} {item.unit}</p></div><strong className="text-sm text-rose-700">{item.expirationDate?.split("-").reverse().join("/")}</strong></div>)}</div> : <div className="flex min-h-48 flex-col items-center justify-center px-5 text-center"><CircleCheck className="h-7 w-7 text-emerald-700/60" /><p className="mt-3 text-sm font-semibold text-[#294239]">Nenhum lote próximo do vencimento.</p><p className="mt-1 text-sm text-slate-500">Acompanhe os lotes com validade pela central específica.</p></div>}</article></section>
      <section className="mt-6 overflow-hidden rounded-2xl border border-white/80 bg-white shadow-[0_10px_28px_rgba(16,24,32,0.06)]"><div className="flex items-center justify-between border-b border-[#e5e8ec] p-5 sm:p-6"><div><p className="text-xs font-bold uppercase tracking-[0.13em] text-slate-500">Auditoria</p><h2 className="mt-1 font-serif text-xl font-semibold text-[#101820]">Reembolsos recentes</h2></div><Button variant="ghost" onClick={() => setLocation("/vendas")} className="h-9 rounded-lg px-2 text-[#8a6207] hover:bg-[#fff6da] hover:text-[#6f4b00]">Histórico <ArrowUpRight className="ml-1 h-4 w-4" /></Button></div>{sensitiveCashEvents.length ? <div>{sensitiveCashEvents.map(item => <div key={item.id} className="flex items-center justify-between gap-4 border-b border-[#edf0f2] px-5 py-4 last:border-0 sm:px-6"><div className="flex min-w-0 items-center gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-amber-100 text-amber-800"><RotateCcw className="h-4 w-4" /></span><div className="min-w-0"><p className="text-sm font-semibold text-[#203a31]">{item.type === "return" ? "Devolução" : "Cancelamento"}</p><p className="mt-0.5 truncate text-xs text-slate-500">{item.description || "Sem observação"}</p></div></div><strong className="text-sm text-amber-700">R$ {toNumber(item.amount).toLocaleString("pt-BR", { minimumFractionDigits: 2 })}</strong></div>)}</div> : <div className="flex min-h-40 flex-col items-center justify-center px-5 text-center"><CircleCheck className="h-7 w-7 text-emerald-700/60" /><p className="mt-3 text-sm font-semibold text-[#294239]">Nenhum reembolso recente.</p><p className="mt-1 text-sm text-slate-500">Cancelamentos e devoluções registrados aparecerão aqui para acompanhamento.</p></div>}</section>
    </>}
  </div>;
}
