import { PageHeader } from "@/components/PageHeader";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { universalHardwareControls } from "@/lib/hardwareAvailability";
import { defaultOperationSettings, listOperationStations, loadOperationSettings, saveOperationSettings, type OperationSettings } from "@/lib/operationSettings";
import { printThermalReceipt } from "@/lib/thermalReceipt";
import { Cable, CheckCircle2, CircleAlert, MessageCircle, Printer, Scale, Store, WalletCards } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

export default function OperationSetup() {
  const [stationName, setStationName] = useState(defaultOperationSettings.stationName);
  const [savedStations, setSavedStations] = useState<string[]>(() => listOperationStations());
  const [settings, setSettings] = useState<OperationSettings>(() => loadOperationSettings());
  const update = <Key extends keyof OperationSettings>(key: Key, value: OperationSettings[Key]) => setSettings(current => ({ ...current, [key]: value }));
  const drawerControl = universalHardwareControls.drawer;
  const scaleControl = universalHardwareControls.scale;

  useEffect(() => {
    if (settings.stationName !== stationName) return;
    saveOperationSettings(settings);
    setSavedStations(listOperationStations());
  }, [settings, stationName]);

  const selectStation = (nextName: string) => {
    const safeName = nextName.trim() || defaultOperationSettings.stationName;
    setStationName(safeName);
    setSettings(loadOperationSettings(safeName));
  };
  const renameStation = () => {
    const nextName = stationName.trim() || defaultOperationSettings.stationName;
    setStationName(nextName);
    setSettings(current => ({ ...current, stationName: nextName }));
  };
  const printTest = () => {
    try {
      printThermalReceipt({ code: "TESTE-TERMICA", issuedAt: new Date(), paymentLabel: "Teste de impressão", subtotal: 0, discount: 0, total: 0, items: [] }, settings.receiptWidth);
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Não foi possível iniciar a impressão.");
    }
  };

  return <div className="mx-auto max-w-[1320px]"><PageHeader eyebrow="Configuração" title="Operação conectada" description="Cada computador pode ter seu próprio perfil de impressora, gaveta, balança e WhatsApp. Nenhuma preferência desta estação interfere nas demais." />
    <section className="mb-5 rounded-2xl border border-[#dce6dd] bg-white p-4 shadow-[0_10px_28px_rgba(37,59,48,0.06)] sm:p-5"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#eaf4ed] text-[#287252]"><Store className="h-5 w-5" /></span><div><p className="text-xs font-bold uppercase tracking-[0.13em] text-slate-500">Perfil desta instalação</p><h2 className="mt-1 font-serif text-xl font-semibold text-[#17332c]">Estação de atendimento</h2></div></div><div className="mt-4 grid gap-3 md:grid-cols-[minmax(0,1fr)_auto]"><label><span className="mb-1.5 block text-sm font-semibold text-[#294239]">Nome da estação</span><Input value={stationName} onChange={event => setStationName(event.target.value)} onBlur={renameStation} placeholder="Ex.: Caixa 1, Balcão ou Entrega" className="h-11 rounded-xl" /></label><div className="md:self-end"><Button type="button" onClick={renameStation} className="h-11 rounded-xl bg-[#173f32] text-white hover:bg-[#103b2d]">Salvar perfil local</Button></div></div>{savedStations.length ? <div className="mt-3 flex flex-wrap items-center gap-2"><span className="text-xs font-semibold text-slate-500">Estações deste computador:</span>{savedStations.map(station => <Button key={station} type="button" onClick={() => selectStation(station)} variant="outline" className={`h-8 rounded-lg px-3 text-xs ${station === settings.stationName ? "border-[#b78311] bg-[#fff7df] text-[#805900]" : "border-[#d5dfd7] text-[#456052]"}`}>{station}</Button>)}</div> : null}<p className="mt-3 text-xs leading-5 text-slate-500">Use um nome diferente em cada computador do cliente. Assim, cada caixa mantém suas próprias preferências, mesmo que os equipamentos sejam de marcas diferentes.</p></section>
    <div className="mb-5 flex items-start gap-3 rounded-xl border border-[#eadfbf] bg-[#fff8e8] px-4 py-3 text-sm leading-6 text-[#6f5311]"><CircleAlert className="mt-0.5 h-4 w-4 shrink-0 text-[#a36c00]" /><p><strong>Modo universal ativo em {settings.stationName}:</strong> o comprovante usa a janela de impressão do navegador. A conexão direta com impressora, gaveta ou balança só será ativada nesta estação após informar o equipamento e instalá-lo no computador do caixa.</p></div>
    <section className="grid gap-5 xl:grid-cols-2"><article className="rounded-2xl border border-white/80 bg-white p-5 shadow-[0_10px_28px_rgba(37,59,48,0.06)] sm:p-6"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#fff2ca] text-[#976800]"><Printer className="h-5 w-5" /></span><div><p className="text-xs font-bold uppercase tracking-[0.13em] text-slate-500">Impressora térmica</p><h2 className="mt-1 font-serif text-xl font-semibold text-[#17332c]">Comprovante pelo navegador</h2></div></div><p className="mt-4 text-sm leading-6 text-slate-600">Ao concluir uma venda, o operador poderá abrir um comprovante compacto e escolher qualquer impressora disponível neste computador.</p><label className="mt-5 block"><span className="mb-2 block text-sm font-semibold text-[#294239]">Largura mais comum do papel</span><div className="grid grid-cols-2 gap-2"><Button type="button" variant="outline" onClick={() => update("receiptWidth", "58")} className={`h-11 rounded-xl ${settings.receiptWidth === "58" ? "border-[#b78311] bg-[#fff7df] text-[#805900]" : "border-[#d5dfd7] text-[#456052]"}`}>58 mm</Button><Button type="button" variant="outline" onClick={() => update("receiptWidth", "80")} className={`h-11 rounded-xl ${settings.receiptWidth === "80" ? "border-[#b78311] bg-[#fff7df] text-[#805900]" : "border-[#d5dfd7] text-[#456052]"}`}>80 mm</Button></div></label><Button type="button" onClick={printTest} className="mt-5 h-11 rounded-xl bg-[#b78311] text-white hover:bg-[#956b0d]"><Printer className="mr-2 h-4 w-4" />Imprimir teste</Button></article>
      <article className="rounded-2xl border border-white/80 bg-white p-5 shadow-[0_10px_28px_rgba(37,59,48,0.06)] sm:p-6"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#e8f4ea] text-[#287252]"><WalletCards className="h-5 w-5" /></span><div><p className="text-xs font-bold uppercase tracking-[0.13em] text-slate-500">Gaveta de dinheiro</p><h2 className="mt-1 font-serif text-xl font-semibold text-[#17332c]">Preparada para o caixa</h2></div></div><p className="mt-4 text-sm leading-6 text-slate-600">A gaveta normalmente é ligada à impressora térmica. A configuração física será específica para este computador.</p><label className="mt-5 flex cursor-pointer items-center gap-3 rounded-xl border border-[#dce6dd] bg-[#f7faf7] p-3"><input checked={settings.drawerOnPrint} onChange={event => update("drawerOnPrint", event.target.checked)} type="checkbox" className="h-4 w-4 accent-[#b78311]" /><span><span className="block text-sm font-semibold text-[#294239]">Abrir junto ao comprovante</span><span className="mt-0.5 block text-xs leading-5 text-slate-500">Preferência salva somente em {settings.stationName}.</span></span></label><Button type="button" disabled className="mt-3 h-10 w-full rounded-xl"><WalletCards className="mr-2 h-4 w-4" />{drawerControl.label}</Button><div className="mt-3 flex items-center gap-2 text-xs font-semibold text-[#847038]"><Cable className="h-4 w-4" />{drawerControl.guidance}</div></article>
      <article className="rounded-2xl border border-white/80 bg-white p-5 shadow-[0_10px_28px_rgba(37,59,48,0.06)] sm:p-6"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#e5effb] text-[#365f96]"><Scale className="h-5 w-5" /></span><div><p className="text-xs font-bold uppercase tracking-[0.13em] text-slate-500">Balança</p><h2 className="mt-1 font-serif text-xl font-semibold text-[#17332c]">Peso manual ou conectado</h2></div></div><p className="mt-4 text-sm leading-6 text-slate-600">O PDV já aceita peso digitado para KG, G, L e outras medidas. A conexão futura ficará separada por estação.</p><div className="mt-5 grid grid-cols-2 gap-2"><Button type="button" variant="outline" onClick={() => update("scaleMode", "manual")} className={`h-11 rounded-xl ${settings.scaleMode === "manual" ? "border-[#4a78b8] bg-[#eef5ff] text-[#2d609f]" : "border-[#d5dfd7] text-[#456052]"}`}>Peso manual</Button><Button type="button" variant="outline" onClick={() => update("scaleMode", "connected")} className={`h-11 rounded-xl ${settings.scaleMode === "connected" ? "border-[#4a78b8] bg-[#eef5ff] text-[#2d609f]" : "border-[#d5dfd7] text-[#456052]"}`}>Preparar conexão</Button></div><Button type="button" disabled className="mt-3 h-10 w-full rounded-xl"><Scale className="mr-2 h-4 w-4" />{scaleControl.label}</Button><p className="mt-3 text-xs leading-5 text-slate-500">{scaleControl.guidance}</p></article>
      <article className="rounded-2xl border border-white/80 bg-white p-5 shadow-[0_10px_28px_rgba(37,59,48,0.06)] sm:p-6"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#e6f3e9] text-[#218554]"><MessageCircle className="h-5 w-5" /></span><div><p className="text-xs font-bold uppercase tracking-[0.13em] text-slate-500">Pedidos por WhatsApp</p><h2 className="mt-1 font-serif text-xl font-semibold text-[#17332c]">Número da loja</h2></div></div><p className="mt-4 text-sm leading-6 text-slate-600">O pedido abre uma conversa no WhatsApp com retirada ou entrega e a forma de pagamento escolhida.</p><label className="mt-5 block"><span className="mb-1.5 block text-sm font-semibold text-[#294239]">WhatsApp deste atendimento</span><Input value={settings.whatsappNumber} onChange={event => update("whatsappNumber", event.target.value)} inputMode="tel" placeholder="Ex.: 55 11 99999-9999" className="h-11 rounded-xl" /><span className="mt-2 block text-xs leading-5 text-slate-500">O número é salvo somente para {settings.stationName} e pode ficar vazio por enquanto.</span></label><div className="mt-5 flex items-center gap-2 text-xs font-semibold text-[#2d7455]"><CheckCircle2 className="h-4 w-4" />Perfil salvo automaticamente neste computador.</div></article></section>
    <button type="button" onClick={() => setSettings({ ...defaultOperationSettings, stationName: settings.stationName })} className="mt-5 text-sm font-semibold text-[#6e7e75] underline-offset-4 hover:underline">Restaurar preferências de {settings.stationName}</button>
  </div>;
}
