import { PageHeader, PrimaryAction } from "@/components/PageHeader";
import { formatCurrency, formatDate, formatQuantity, toNumber } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { BarChart3, CircleAlert, CircleDollarSign, FileDown, Loader2, TrendingUp, WalletCards } from "lucide-react";
import { toast } from "sonner";

export default function Reports() {
  const { data, isLoading, error } = trpc.reports.overview.useQuery();
  const ticketAverage = data?.salesTodayCount ? data.salesTodayAmount / data.salesTodayCount : 0;
  const productsSold = data?.topProducts.reduce((sum, product) => sum + toNumber(product.quantity), 0) ?? 0;
  const movementLabel: Record<string, string> = { sale: "Venda", supply: "Suprimento", withdrawal: "Sangria", adjustment: "Ajuste", cancellation: "Cancelamento" };
  const exportReport = () => {
    if (!data) { toast.error("Aguarde os dados do relatório serem carregados."); return; }
    const lines = [
      ["Relatório operacional", "Valor"],
      ["Faturamento hoje", data.salesTodayAmount],
      ["Vendas concluídas", data.salesTodayCount],
      ["Ticket médio", ticketAverage],
      [],
      ["Produtos mais vendidos", "Quantidade", "Receita"],
      ...data.topProducts.map(product => [product.productName, product.quantity, product.revenue]),
      [],
      ["Estoque em atenção", "Estoque", "Mínimo"],
      ...data.lowStockItems.map(product => [product.name, product.stockQuantity, product.minimumStock]),
    ];
    const csv = lines.map(row => row.map(value => `"${String(value ?? "").replaceAll('"', '""')}"`).join(";")).join("\n");
    const link = document.createElement("a");
    link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" }));
    link.download = "relatorio-operacional.csv";
    link.click();
    URL.revokeObjectURL(link.href);
    toast.success("Relatório exportado em CSV.");
  };

  return <div className="mx-auto max-w-[1480px]">
    <PageHeader eyebrow="Análise" title="Relatórios" description="Transforme as movimentações da loja em uma leitura objetiva para orientar compras, vendas e controle financeiro." action={<PrimaryAction onClick={exportReport}><FileDown className="mr-2 h-4 w-4" />Exportar relatório</PrimaryAction>} />
    {isLoading ? <div className="mb-4 flex items-center gap-2 text-sm text-slate-500"><Loader2 className="h-4 w-4 animate-spin" />Consolidando dados...</div> : null}
    {error ? <div className="mb-4 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">Os relatórios estão disponíveis para administradores e gerentes.</div> : null}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><article className="rounded-2xl border border-white/80 bg-white p-5 shadow-[0_10px_28px_rgba(37,59,48,0.06)]"><p className="text-xs font-bold uppercase tracking-[0.13em] text-slate-500">Faturamento hoje</p><p className="mt-5 font-serif text-3xl font-semibold text-[#17332c]">{formatCurrency(data?.salesTodayAmount)}</p><p className="mt-1 text-xs text-slate-500">Vendas concluídas no dia</p></article><article className="rounded-2xl border border-white/80 bg-white p-5 shadow-[0_10px_28px_rgba(37,59,48,0.06)]"><p className="text-xs font-bold uppercase tracking-[0.13em] text-slate-500">Vendas concluídas</p><p className="mt-5 font-serif text-3xl font-semibold text-[#17332c]">{data?.salesTodayCount ?? 0}</p><p className="mt-1 text-xs text-slate-500">No período atual</p></article><article className="rounded-2xl border border-white/80 bg-white p-5 shadow-[0_10px_28px_rgba(37,59,48,0.06)]"><p className="text-xs font-bold uppercase tracking-[0.13em] text-slate-500">Ticket médio</p><p className="mt-5 font-serif text-3xl font-semibold text-[#17332c]">{formatCurrency(ticketAverage)}</p><p className="mt-1 text-xs text-slate-500">Média por atendimento</p></article><article className="rounded-2xl border border-white/80 bg-white p-5 shadow-[0_10px_28px_rgba(37,59,48,0.06)]"><p className="text-xs font-bold uppercase tracking-[0.13em] text-slate-500">Produtos vendidos</p><p className="mt-5 font-serif text-3xl font-semibold text-[#17332c]">{formatQuantity(productsSold)}</p><p className="mt-1 text-xs text-slate-500">Unidades no período</p></article></section>
    <section className="mt-6 grid gap-5 xl:grid-cols-2"><article className="overflow-hidden rounded-2xl border border-white/80 bg-white shadow-[0_10px_28px_rgba(37,59,48,0.06)]"><div className="flex items-center justify-between border-b border-[#e5ebe5] p-5 sm:p-6"><div><p className="text-xs font-bold uppercase tracking-[0.13em] text-slate-500">Vendas por produto</p><h2 className="mt-1 font-serif text-xl font-semibold text-[#17332c]">Mais vendidos</h2></div><span className="rounded-lg bg-[#eef5ee] px-3 py-1.5 text-xs font-semibold text-emerald-800">Por quantidade</span></div>{data?.topProducts.length ? <div>{data.topProducts.map((product, index) => <div key={product.productName} className="grid grid-cols-[30px_1fr_auto] items-center gap-3 border-b border-[#edf0ed] px-5 py-4 last:border-0"><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-[#edf5ee] text-xs font-bold text-emerald-800">{index + 1}</span><div className="min-w-0"><p className="truncate text-sm font-semibold text-[#294239]">{product.productName}</p><p className="mt-1 text-xs text-slate-500">{formatQuantity(product.quantity)} unidade(s) vendida(s)</p></div><strong className="text-sm text-[#294239]">{formatCurrency(product.revenue)}</strong></div>)}</div> : <div className="flex min-h-[250px] flex-col items-center justify-center px-5 text-center"><BarChart3 className="h-7 w-7 text-emerald-700/45" /><p className="mt-3 text-sm font-semibold text-[#294239]">Ainda não há vendas para analisar.</p><p className="mt-1 text-sm text-slate-500">Os produtos mais vendidos aparecerão depois das primeiras vendas.</p></div>}</article>
      <article className="overflow-hidden rounded-2xl border border-white/80 bg-white shadow-[0_10px_28px_rgba(37,59,48,0.06)]"><div className="flex items-center justify-between border-b border-[#e5ebe5] p-5 sm:p-6"><div><p className="text-xs font-bold uppercase tracking-[0.13em] text-slate-500">Reposição</p><h2 className="mt-1 font-serif text-xl font-semibold text-[#17332c]">Estoque em atenção</h2></div><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-amber-100 text-amber-800"><CircleAlert className="h-5 w-5" /></span></div>{data?.lowStockItems.length ? <div>{data.lowStockItems.map(product => <div key={product.id} className="grid grid-cols-[1fr_auto] items-center gap-3 border-b border-[#edf0ed] px-5 py-4 last:border-0"><div><p className="text-sm font-semibold text-[#294239]">{product.name}</p><p className="mt-1 text-xs text-slate-500">Mínimo recomendado: {formatQuantity(product.minimumStock)} {product.unit}</p></div><strong className="rounded-lg bg-amber-100 px-2.5 py-1.5 text-sm text-amber-800">{formatQuantity(product.stockQuantity)} {product.unit}</strong></div>)}</div> : <div className="flex min-h-[250px] flex-col items-center justify-center px-5 text-center"><CircleAlert className="h-7 w-7 text-emerald-700/45" /><p className="mt-3 text-sm font-semibold text-[#294239]">Nenhum produto abaixo do mínimo.</p><p className="mt-1 text-sm text-slate-500">Mantenha os níveis mínimos atualizados no catálogo.</p></div>}</article></section>
    <section className="mt-6 overflow-hidden rounded-2xl border border-white/80 bg-white shadow-[0_10px_28px_rgba(37,59,48,0.06)]"><div className="flex items-center justify-between border-b border-[#e5ebe5] p-5 sm:p-6"><div><p className="text-xs font-bold uppercase tracking-[0.13em] text-slate-500">Conciliação</p><h2 className="mt-1 font-serif text-xl font-semibold text-[#17332c]">Movimentação de caixa</h2></div><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#e6f3e9] text-emerald-800"><WalletCards className="h-5 w-5" /></span></div>{data?.latestCashMovements.length ? <div>{data.latestCashMovements.map(movement => <div key={movement.id} className="grid grid-cols-[1fr_auto] gap-3 border-b border-[#edf0ed] px-5 py-4 last:border-0 sm:grid-cols-[1.3fr_1fr_auto]"><div><p className="text-sm font-semibold text-[#294239]">{movementLabel[movement.type]}</p><p className="mt-1 text-xs text-slate-500">{movement.description || movement.paymentMethod || "Sem observação"}</p></div><span className="hidden text-sm text-slate-500 sm:block">{formatDate(movement.createdAt)}</span><strong className={movement.type === "withdrawal" || movement.type === "cancellation" ? "text-right text-amber-700" : "text-right text-emerald-800"}>{movement.type === "withdrawal" || movement.type === "cancellation" ? "− " : "+ "}{formatCurrency(movement.amount)}</strong></div>)}</div> : <div className="flex min-h-[190px] flex-col items-center justify-center px-5 text-center"><CircleDollarSign className="h-7 w-7 text-emerald-700/45" /><p className="mt-3 text-sm font-semibold text-[#294239]">Nenhuma movimentação de caixa no período.</p><p className="mt-1 text-sm text-slate-500">Aberturas, suprimentos, sangrias e vendas aparecerão neste relatório.</p></div>}</section>
    <section className="mt-6 grid gap-4 md:grid-cols-2"><article className="rounded-2xl border border-[#dce6dd] bg-[#eef5ee] p-5"><TrendingUp className="h-5 w-5 text-emerald-800" /><p className="mt-3 text-sm font-semibold text-[#244334]">Indicadores de venda</p><p className="mt-1 text-sm leading-6 text-slate-600">Acompanhe faturamento, volume e ticket médio no período atual.</p></article><article className="rounded-2xl border border-[#f1deb2] bg-[#fffaf0] p-5"><CircleAlert className="h-5 w-5 text-amber-700" /><p className="mt-3 text-sm font-semibold text-[#5c4420]">Prioridade de reposição</p><p className="mt-1 text-sm leading-6 text-[#806a45]">Os itens com saldo igual ou inferior ao mínimo ficam destacados para apoiar a próxima compra.</p></article></section>
  </div>;
}
