import { PageHeader, PrimaryAction } from "@/components/PageHeader";
import { QueryAlert } from "@/components/QueryAlert";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { formatQuantity } from "@/lib/format";
import { getShelfLifeInfo } from "@/lib/shelfLife";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, CalendarClock, ClipboardMinus, Loader2, PackageCheck, PackageX } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { toast } from "sonner";

export default function ShelfLife() {
  const [receiveOpen, setReceiveOpen] = useState(false);
  const [lossOpen, setLossOpen] = useState(false);
  const [productId, setProductId] = useState("");
  const [supplierId, setSupplierId] = useState("");
  const [batchCode, setBatchCode] = useState("");
  const [expirationDate, setExpirationDate] = useState("");
  const [quantity, setQuantity] = useState("");
  const [unitCost, setUnitCost] = useState("");
  const [lossProductId, setLossProductId] = useState("");
  const [lossBatchId, setLossBatchId] = useState("");
  const [lossQuantity, setLossQuantity] = useState("");
  const [lossReason, setLossReason] = useState("");
  const utils = trpc.useUtils();
  const { data: batches, isLoading, error, refetch } = trpc.stock.batches.useQuery();
  const { data: products } = trpc.catalog.products.list.useQuery();
  const { data: suppliers } = trpc.catalog.suppliers.list.useQuery();
  const batchesForLossProduct = useMemo(() => batches?.filter(batch => batch.productId === Number(lossProductId)) ?? [], [batches, lossProductId]);
  const expiringSoon = useMemo(() => batches?.filter(batch => { const { days } = getShelfLifeInfo(batch.expirationDate); return days !== null && days <= 7; }) ?? [], [batches]);

  const resetReceive = () => { setReceiveOpen(false); setProductId(""); setSupplierId(""); setBatchCode(""); setExpirationDate(""); setQuantity(""); setUnitCost(""); };
  const resetLoss = () => { setLossOpen(false); setLossProductId(""); setLossBatchId(""); setLossQuantity(""); setLossReason(""); };
  const receiveBatch = trpc.stock.receiveBatch.useMutation({ onSuccess: async result => { await Promise.all([utils.stock.batches.invalidate(), utils.stock.movements.invalidate(), utils.catalog.products.list.invalidate(), utils.dashboard.summary.invalidate()]); toast.success(`Lote ${result.batchCode} recebido. Estoque atualizado.`); resetReceive(); }, onError: issue => toast.error(issue.message) });
  const recordLoss = trpc.stock.registerLoss.useMutation({ onSuccess: async result => { await Promise.all([utils.stock.batches.invalidate(), utils.stock.movements.invalidate(), utils.catalog.products.list.invalidate(), utils.dashboard.summary.invalidate()]); toast.success(`Perda registrada. Saldo atual: ${formatQuantity(result.currentQuantity)}.`); resetLoss(); }, onError: issue => toast.error(issue.message) });
  const submitReceive = (event: FormEvent) => { event.preventDefault(); receiveBatch.mutate({ productId: Number(productId), supplierId: supplierId ? Number(supplierId) : null, batchCode: batchCode || undefined, expirationDate: expirationDate || undefined, quantity: Number(quantity), unitCost: unitCost ? Number(unitCost) : undefined }); };
  const submitLoss = (event: FormEvent) => { event.preventDefault(); recordLoss.mutate({ productId: Number(lossProductId), batchId: lossBatchId ? Number(lossBatchId) : null, quantity: Number(lossQuantity), reason: lossReason }); };

  return <div className="mx-auto max-w-[1480px]">
    <PageHeader eyebrow="Prevenção de perdas" title="Validade e perdas" description="Registre lotes, acompanhe prazos de vencimento e dê baixa rastreável em avarias, descarte e produtos vencidos." action={<div className="flex flex-wrap gap-2"><Button onClick={() => setLossOpen(true)} variant="outline" className="h-11 rounded-xl border-amber-300 bg-white text-amber-800 hover:bg-amber-50"><PackageX className="mr-2 h-4 w-4" />Registrar perda</Button><PrimaryAction onClick={() => setReceiveOpen(true)}><PackageCheck className="mr-2 h-4 w-4" />Receber lote</PrimaryAction></div>} />
    {error ? <QueryAlert message="Não foi possível carregar os lotes cadastrados." onRetry={() => refetch()} /> : null}
    <section className="grid gap-4 md:grid-cols-3"><article className="rounded-2xl border border-white/80 bg-white p-5 shadow-[0_10px_28px_rgba(37,59,48,0.06)]"><div className="flex items-start justify-between"><p className="text-xs font-bold uppercase tracking-[0.13em] text-slate-500">Lotes ativos</p><span className="rounded-xl bg-emerald-100 p-2.5 text-emerald-800"><PackageCheck className="h-5 w-5" /></span></div><p className="mt-5 font-serif text-3xl font-semibold text-[#17332c]">{batches?.length ?? 0}</p><p className="mt-1 text-xs text-slate-500">Com saldo disponível para venda</p></article><article className="rounded-2xl border border-white/80 bg-white p-5 shadow-[0_10px_28px_rgba(37,59,48,0.06)]"><div className="flex items-start justify-between"><p className="text-xs font-bold uppercase tracking-[0.13em] text-slate-500">Vencem em 7 dias</p><span className="rounded-xl bg-amber-100 p-2.5 text-amber-800"><CalendarClock className="h-5 w-5" /></span></div><p className="mt-5 font-serif text-3xl font-semibold text-[#17332c]">{expiringSoon.length}</p><p className="mt-1 text-xs text-slate-500">Priorize venda, promoção ou descarte</p></article><article className="rounded-2xl border border-white/80 bg-white p-5 shadow-[0_10px_28px_rgba(37,59,48,0.06)]"><div className="flex items-start justify-between"><p className="text-xs font-bold uppercase tracking-[0.13em] text-slate-500">Boas práticas</p><span className="rounded-xl bg-sky-100 p-2.5 text-sky-800"><AlertTriangle className="h-5 w-5" /></span></div><p className="mt-5 font-serif text-xl font-semibold text-[#17332c]">Primeiro que vence</p><p className="mt-1 text-xs text-slate-500">Organize a gôndola seguindo a validade</p></article></section>
    <section className="mt-6 overflow-hidden rounded-2xl border border-white/80 bg-white shadow-[0_10px_28px_rgba(37,59,48,0.06)]"><div className="flex items-center justify-between border-b border-[#e5ebe5] p-5 sm:p-6"><div><p className="text-xs font-bold uppercase tracking-[0.13em] text-slate-500">Rastreabilidade</p><h2 className="mt-1 font-serif text-xl font-semibold text-[#17332c]">Lotes cadastrados</h2></div><span className="rounded-lg bg-[#eef5ee] px-3 py-1.5 text-xs font-semibold text-emerald-800">Ordenado por validade</span></div>{isLoading ? <div className="flex min-h-64 items-center justify-center gap-2 text-sm text-slate-500"><Loader2 className="h-4 w-4 animate-spin" />Carregando lotes...</div> : batches?.length ? <div>{batches.map(batch => { const expiry = getShelfLifeInfo(batch.expirationDate); return <div key={batch.id} className="grid gap-3 border-b border-[#edf0ed] px-5 py-4 last:border-0 sm:grid-cols-[1.4fr_1fr_auto_auto] sm:items-center"><div><p className="text-sm font-semibold text-[#294239]">{batch.productName}</p><p className="mt-1 text-xs text-slate-500">Lote: {batch.code || "Sem identificação"}{batch.supplierName ? ` · ${batch.supplierName}` : ""}</p></div><span className={`w-fit rounded-lg px-2.5 py-1.5 text-xs font-semibold ${expiry.tone}`}>{expiry.label}</span><span className="text-sm text-slate-600">{formatQuantity(batch.availableQuantity)} {batch.unit}</span><button onClick={() => { setLossProductId(String(batch.productId)); setLossBatchId(String(batch.id)); setLossOpen(true); }} className="flex w-fit items-center gap-1.5 rounded-lg bg-amber-50 px-2.5 py-1.5 text-xs font-semibold text-amber-800 hover:bg-amber-100"><ClipboardMinus className="h-3.5 w-3.5" />Dar baixa</button></div>; })}</div> : <div className="flex min-h-72 flex-col items-center justify-center px-5 text-center"><CalendarClock className="h-8 w-8 text-emerald-700/45" /><p className="mt-4 text-sm font-semibold text-[#294239]">Nenhum lote registrado.</p><p className="mt-1 max-w-md text-sm leading-6 text-slate-500">Use “Receber lote” para acompanhar produtos perecíveis desde a entrada até a venda ou baixa por perda.</p></div>}</section>
    <Dialog open={receiveOpen} onOpenChange={isOpen => !isOpen && resetReceive()}><DialogContent className="max-h-[90vh] overflow-y-auto rounded-2xl sm:max-w-lg"><DialogHeader><DialogTitle className="font-serif text-2xl text-[#17332c]">Receber lote</DialogTitle><DialogDescription>Registre a entrada com identificação e validade para acompanhar produtos perecíveis.</DialogDescription></DialogHeader><form onSubmit={submitReceive} className="space-y-4 pt-2"><label><span className="mb-1.5 block text-sm font-semibold text-[#294239]">Produto</span><select required value={productId} onChange={event => setProductId(event.target.value)} className="h-11 w-full rounded-xl border border-input bg-background px-3 text-sm"><option value="">Selecione um produto</option>{products?.map(product => <option key={product.id} value={product.id}>{product.name}</option>)}</select></label><label><span className="mb-1.5 block text-sm font-semibold text-[#294239]">Fornecedor</span><select value={supplierId} onChange={event => setSupplierId(event.target.value)} className="h-11 w-full rounded-xl border border-input bg-background px-3 text-sm"><option value="">Não vincular fornecedor</option>{suppliers?.map(supplier => <option key={supplier.id} value={supplier.id}>{supplier.tradeName || supplier.legalName}</option>)}</select></label><div className="grid gap-4 sm:grid-cols-2"><label><span className="mb-1.5 block text-sm font-semibold text-[#294239]">Código do lote</span><Input value={batchCode} onChange={event => setBatchCode(event.target.value)} placeholder="Opcional" className="h-11 rounded-xl" /></label><label><span className="mb-1.5 block text-sm font-semibold text-[#294239]">Validade</span><Input type="date" value={expirationDate} onChange={event => setExpirationDate(event.target.value)} className="h-11 rounded-xl" /></label><label><span className="mb-1.5 block text-sm font-semibold text-[#294239]">Quantidade</span><Input required type="number" min="0.001" step="0.001" value={quantity} onChange={event => setQuantity(event.target.value)} className="h-11 rounded-xl" /></label><label><span className="mb-1.5 block text-sm font-semibold text-[#294239]">Custo unitário</span><Input type="number" min="0" step="0.01" value={unitCost} onChange={event => setUnitCost(event.target.value)} placeholder="Opcional" className="h-11 rounded-xl" /></label></div><div className="flex justify-end gap-2 pt-2"><Button type="button" variant="outline" onClick={resetReceive} className="h-11 rounded-xl">Cancelar</Button><Button disabled={receiveBatch.isPending} className="h-11 rounded-xl bg-[#164e3d] text-white hover:bg-[#0f4032]">{receiveBatch.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Receber lote</Button></div></form></DialogContent></Dialog>
    <Dialog open={lossOpen} onOpenChange={isOpen => !isOpen && resetLoss()}><DialogContent className="max-h-[90vh] overflow-y-auto rounded-2xl sm:max-w-lg"><DialogHeader><DialogTitle className="font-serif text-2xl text-[#17332c]">Registrar perda</DialogTitle><DialogDescription>Use para avaria, vencimento, quebra ou descarte. A baixa ficará registrada no histórico do estoque.</DialogDescription></DialogHeader><form onSubmit={submitLoss} className="space-y-4 pt-2"><label><span className="mb-1.5 block text-sm font-semibold text-[#294239]">Produto</span><select required value={lossProductId} onChange={event => { setLossProductId(event.target.value); setLossBatchId(""); }} className="h-11 w-full rounded-xl border border-input bg-background px-3 text-sm"><option value="">Selecione um produto</option>{products?.map(product => <option key={product.id} value={product.id}>{product.name}</option>)}</select></label><label><span className="mb-1.5 block text-sm font-semibold text-[#294239]">Lote</span><select value={lossBatchId} onChange={event => setLossBatchId(event.target.value)} disabled={!lossProductId} className="h-11 w-full rounded-xl border border-input bg-background px-3 text-sm"><option value="">Não vincular lote</option>{batchesForLossProduct.map(batch => <option key={batch.id} value={batch.id}>{batch.code || "Lote sem código"} · {formatQuantity(batch.availableQuantity)} {batch.unit}</option>)}</select></label><div className="grid gap-4 sm:grid-cols-2"><label><span className="mb-1.5 block text-sm font-semibold text-[#294239]">Quantidade perdida</span><Input required type="number" min="0.001" step="0.001" value={lossQuantity} onChange={event => setLossQuantity(event.target.value)} className="h-11 rounded-xl" /></label><label><span className="mb-1.5 block text-sm font-semibold text-[#294239]">Motivo</span><Input required minLength={3} value={lossReason} onChange={event => setLossReason(event.target.value)} placeholder="Ex.: vencimento" className="h-11 rounded-xl" /></label></div><div className="flex justify-end gap-2 pt-2"><Button type="button" variant="outline" onClick={resetLoss} className="h-11 rounded-xl">Cancelar</Button><Button disabled={recordLoss.isPending} className="h-11 rounded-xl bg-amber-700 text-white hover:bg-amber-800">{recordLoss.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Registrar perda</Button></div></form></DialogContent></Dialog>
  </div>;
}
